-- Run this in Supabase SQL editor. Required for the Memory tab's search bar.
-- Assumes memory_summaries table has a `embedding vector(1536)` column
-- (or whatever dimension your embedding model produces) and pgvector is enabled.

create or replace function search_memories(
  user_id uuid,
  query_text text,
  match_count int default 10
)
returns table (
  id uuid,
  title text,
  content text,
  skill_tag text,
  created_at timestamptz,
  similarity float
)
language plpgsql
as $$
declare
  query_embedding vector(1536);
begin
  -- The embedding for query_text must be generated by your backend
  -- (Rivet Core) and passed in, OR call an edge function here.
  -- This SQL assumes Rivet Core embeds the query and inserts it into a
  -- temp lookup — adjust to match your actual embedding pipeline.

  return query
  select
    m.id,
    m.title,
    m.content,
    m.skill_tag,
    m.created_at,
    1 - (m.embedding <=> query_embedding) as similarity
  from memory_summaries m
  where m.user_id = search_memories.user_id
  order by m.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- Note: in practice, embedding generation usually happens server-side
-- (Rivet Core calls the embedding model, then queries Supabase directly
-- with the vector). This RPC stub is here so the frontend call signature
-- in useMemory.ts has something to target — confirm the real contract
-- with whoever builds the embedding pipeline.
